export const TRANSACTION_SYNC_CONFIG = {
  DEFAULT_DATE_RANGE_MONTHS: 3,
  MIN_DATE_RANGE_MONTHS: 1,
  MAX_DATE_RANGE_MONTHS: 24,
  WEBHOOK_LOOKBACK_DAYS: 7,
  STATUS_UPDATE_LOOKBACK_DAYS: 30,
} as const;